package com.sentinel.api.domain.estacao;

public enum EstacaoLinha8 {
    AMADOR_BUENO,
    ITAPEVI,
    SANTA_RITA,
    COTIA,
    ENGENHEIRO_CARDOSO,
    JARDIM_SILVEIRA,
    JARDIM_BELVAL,
    BARUERI,
    ANHANGUERA,
    SANTANA_DE_PARNAIBA,
    JARDIM_SANTA_TEREZA,
    OSASCO,
    COMANDANTE_SIQUEIRA,
    PRESIDENTE_ALTINO,
    IMPERATRIZ_LEOPOLDINA,
    DOMINGOS_DE_MORAES,
    LAPA,
    JULIO_PRESTES
}
